/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ProxyAdminInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSigner"
      | "approveUpgrade"
      | "cancelUpgrade"
      | "executeUpgrade"
      | "getPendingUpgradeCount"
      | "getSigners"
      | "getUpgrade"
      | "hasApproved"
      | "isSigner"
      | "owner"
      | "pendingUpgrades"
      | "removeSigner"
      | "scheduleUpgrade"
      | "signers"
      | "threshold"
      | "transferOwnership"
      | "updateThreshold"
      | "upgradeDelay"
      | "upgradeIds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "SignerAdded"
      | "SignerRemoved"
      | "ThresholdUpdated"
      | "UpgradeApproved"
      | "UpgradeCancelled"
      | "UpgradeExecuted"
      | "UpgradeScheduled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveUpgrade",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelUpgrade",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeUpgrade",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingUpgradeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSigners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUpgrade",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingUpgrades",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleUpgrade",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeIds",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingUpgradeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSigners", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUpgrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSigner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingUpgrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeIds", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerAddedEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerRemovedEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [
    oldThreshold: BigNumberish,
    newThreshold: BigNumberish
  ];
  export type OutputTuple = [oldThreshold: bigint, newThreshold: bigint];
  export interface OutputObject {
    oldThreshold: bigint;
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeApprovedEvent {
  export type InputTuple = [upgradeId: BytesLike, signer: AddressLike];
  export type OutputTuple = [upgradeId: string, signer: string];
  export interface OutputObject {
    upgradeId: string;
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeCancelledEvent {
  export type InputTuple = [upgradeId: BytesLike];
  export type OutputTuple = [upgradeId: string];
  export interface OutputObject {
    upgradeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeExecutedEvent {
  export type InputTuple = [
    upgradeId: BytesLike,
    proxy: AddressLike,
    newImplementation: AddressLike
  ];
  export type OutputTuple = [
    upgradeId: string,
    proxy: string,
    newImplementation: string
  ];
  export interface OutputObject {
    upgradeId: string;
    proxy: string;
    newImplementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeScheduledEvent {
  export type InputTuple = [
    upgradeId: BytesLike,
    proxy: AddressLike,
    newImplementation: AddressLike,
    scheduledAt: BigNumberish,
    executeAfter: BigNumberish
  ];
  export type OutputTuple = [
    upgradeId: string,
    proxy: string,
    newImplementation: string,
    scheduledAt: bigint,
    executeAfter: bigint
  ];
  export interface OutputObject {
    upgradeId: string;
    proxy: string;
    newImplementation: string;
    scheduledAt: bigint;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProxyAdmin extends BaseContract {
  connect(runner?: ContractRunner | null): ProxyAdmin;
  waitForDeployment(): Promise<this>;

  interface: ProxyAdminInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSigner: TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;

  approveUpgrade: TypedContractMethod<
    [upgradeId: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelUpgrade: TypedContractMethod<
    [upgradeId: BytesLike],
    [void],
    "nonpayable"
  >;

  executeUpgrade: TypedContractMethod<
    [upgradeId: BytesLike],
    [void],
    "nonpayable"
  >;

  getPendingUpgradeCount: TypedContractMethod<[], [bigint], "view">;

  getSigners: TypedContractMethod<[], [string[]], "view">;

  getUpgrade: TypedContractMethod<
    [upgradeId: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        proxy: string;
        newImplementation: string;
        scheduledAt: bigint;
        approvals: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  hasApproved: TypedContractMethod<
    [upgradeId: BytesLike, signer: AddressLike],
    [boolean],
    "view"
  >;

  isSigner: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingUpgrades: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, boolean] & {
        proxy: string;
        newImplementation: string;
        data: string;
        scheduledAt: bigint;
        approvals: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  removeSigner: TypedContractMethod<
    [signer: AddressLike],
    [void],
    "nonpayable"
  >;

  scheduleUpgrade: TypedContractMethod<
    [proxy: AddressLike, newImplementation: AddressLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  signers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  threshold: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeDelay: TypedContractMethod<[], [bigint], "view">;

  upgradeIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSigner"
  ): TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveUpgrade"
  ): TypedContractMethod<[upgradeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelUpgrade"
  ): TypedContractMethod<[upgradeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeUpgrade"
  ): TypedContractMethod<[upgradeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPendingUpgradeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSigners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUpgrade"
  ): TypedContractMethod<
    [upgradeId: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        proxy: string;
        newImplementation: string;
        scheduledAt: bigint;
        approvals: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [upgradeId: BytesLike, signer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSigner"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingUpgrades"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, boolean] & {
        proxy: string;
        newImplementation: string;
        data: string;
        scheduledAt: bigint;
        approvals: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeSigner"
  ): TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scheduleUpgrade"
  ): TypedContractMethod<
    [proxy: AddressLike, newImplementation: AddressLike, data: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "threshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "upgradeIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SignerAdded"
  ): TypedContractEvent<
    SignerAddedEvent.InputTuple,
    SignerAddedEvent.OutputTuple,
    SignerAddedEvent.OutputObject
  >;
  getEvent(
    key: "SignerRemoved"
  ): TypedContractEvent<
    SignerRemovedEvent.InputTuple,
    SignerRemovedEvent.OutputTuple,
    SignerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdUpdated"
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeApproved"
  ): TypedContractEvent<
    UpgradeApprovedEvent.InputTuple,
    UpgradeApprovedEvent.OutputTuple,
    UpgradeApprovedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeCancelled"
  ): TypedContractEvent<
    UpgradeCancelledEvent.InputTuple,
    UpgradeCancelledEvent.OutputTuple,
    UpgradeCancelledEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeExecuted"
  ): TypedContractEvent<
    UpgradeExecutedEvent.InputTuple,
    UpgradeExecutedEvent.OutputTuple,
    UpgradeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeScheduled"
  ): TypedContractEvent<
    UpgradeScheduledEvent.InputTuple,
    UpgradeScheduledEvent.OutputTuple,
    UpgradeScheduledEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SignerAdded(address)": TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;
    SignerAdded: TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;

    "SignerRemoved(address)": TypedContractEvent<
      SignerRemovedEvent.InputTuple,
      SignerRemovedEvent.OutputTuple,
      SignerRemovedEvent.OutputObject
    >;
    SignerRemoved: TypedContractEvent<
      SignerRemovedEvent.InputTuple,
      SignerRemovedEvent.OutputTuple,
      SignerRemovedEvent.OutputObject
    >;

    "ThresholdUpdated(uint256,uint256)": TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;

    "UpgradeApproved(bytes32,address)": TypedContractEvent<
      UpgradeApprovedEvent.InputTuple,
      UpgradeApprovedEvent.OutputTuple,
      UpgradeApprovedEvent.OutputObject
    >;
    UpgradeApproved: TypedContractEvent<
      UpgradeApprovedEvent.InputTuple,
      UpgradeApprovedEvent.OutputTuple,
      UpgradeApprovedEvent.OutputObject
    >;

    "UpgradeCancelled(bytes32)": TypedContractEvent<
      UpgradeCancelledEvent.InputTuple,
      UpgradeCancelledEvent.OutputTuple,
      UpgradeCancelledEvent.OutputObject
    >;
    UpgradeCancelled: TypedContractEvent<
      UpgradeCancelledEvent.InputTuple,
      UpgradeCancelledEvent.OutputTuple,
      UpgradeCancelledEvent.OutputObject
    >;

    "UpgradeExecuted(bytes32,address,address)": TypedContractEvent<
      UpgradeExecutedEvent.InputTuple,
      UpgradeExecutedEvent.OutputTuple,
      UpgradeExecutedEvent.OutputObject
    >;
    UpgradeExecuted: TypedContractEvent<
      UpgradeExecutedEvent.InputTuple,
      UpgradeExecutedEvent.OutputTuple,
      UpgradeExecutedEvent.OutputObject
    >;

    "UpgradeScheduled(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      UpgradeScheduledEvent.InputTuple,
      UpgradeScheduledEvent.OutputTuple,
      UpgradeScheduledEvent.OutputObject
    >;
    UpgradeScheduled: TypedContractEvent<
      UpgradeScheduledEvent.InputTuple,
      UpgradeScheduledEvent.OutputTuple,
      UpgradeScheduledEvent.OutputObject
    >;
  };
}
