/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RedPocketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ETH_ADDRESS"
      | "MAX_EXPIRY_DURATION"
      | "MIN_EXPIRY_DURATION"
      | "canClaim"
      | "claim"
      | "claimDirect"
      | "createETHPocket"
      | "createTokenPocket"
      | "deactivatePocket"
      | "getPocket"
      | "hasClaimed"
      | "isExpired"
      | "operators"
      | "owner"
      | "pocketCounter"
      | "pockets"
      | "recoverExpired"
      | "renounceOwnership"
      | "setOperator"
      | "socialIdClaimed"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OperatorUpdated"
      | "OwnershipTransferred"
      | "PocketClaimed"
      | "PocketCreated"
      | "PocketExpired"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ETH_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EXPIRY_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_EXPIRY_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canClaim",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDirect",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createETHPocket",
    values: [
      BigNumberish,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createTokenPocket",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivatePocket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPocket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pocketCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pockets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "socialIdClaimed",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ETH_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EXPIRY_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_EXPIRY_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimDirect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createETHPocket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTokenPocket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivatePocket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPocket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pocketCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pockets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoverExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "socialIdClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [operator: AddressLike, status: boolean];
  export type OutputTuple = [operator: string, status: boolean];
  export interface OutputObject {
    operator: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PocketClaimedEvent {
  export type InputTuple = [
    pocketId: BigNumberish,
    claimer: AddressLike,
    socialIdHash: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    pocketId: bigint,
    claimer: string,
    socialIdHash: string,
    amount: bigint
  ];
  export interface OutputObject {
    pocketId: bigint;
    claimer: string;
    socialIdHash: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PocketCreatedEvent {
  export type InputTuple = [
    pocketId: BigNumberish,
    creator: AddressLike,
    token: AddressLike,
    totalAmount: BigNumberish,
    totalCount: BigNumberish,
    isLuckyDraw: boolean,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    pocketId: bigint,
    creator: string,
    token: string,
    totalAmount: bigint,
    totalCount: bigint,
    isLuckyDraw: boolean,
    expiresAt: bigint
  ];
  export interface OutputObject {
    pocketId: bigint;
    creator: string;
    token: string;
    totalAmount: bigint;
    totalCount: bigint;
    isLuckyDraw: boolean;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PocketExpiredEvent {
  export type InputTuple = [
    pocketId: BigNumberish,
    refundedAmount: BigNumberish,
    refundTo: AddressLike
  ];
  export type OutputTuple = [
    pocketId: bigint,
    refundedAmount: bigint,
    refundTo: string
  ];
  export interface OutputObject {
    pocketId: bigint;
    refundedAmount: bigint;
    refundTo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RedPocket extends BaseContract {
  connect(runner?: ContractRunner | null): RedPocket;
  waitForDeployment(): Promise<this>;

  interface: RedPocketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ETH_ADDRESS: TypedContractMethod<[], [string], "view">;

  MAX_EXPIRY_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_EXPIRY_DURATION: TypedContractMethod<[], [bigint], "view">;

  canClaim: TypedContractMethod<
    [pocketId: BigNumberish, claimer: AddressLike, socialIdHash: BytesLike],
    [boolean],
    "view"
  >;

  claim: TypedContractMethod<
    [pocketId: BigNumberish, claimer: AddressLike, socialIdHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  claimDirect: TypedContractMethod<
    [pocketId: BigNumberish, socialIdHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  createETHPocket: TypedContractMethod<
    [
      totalCount: BigNumberish,
      isLuckyDraw: boolean,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      expiresAt: BigNumberish,
      platform: string,
      channelId: string
    ],
    [bigint],
    "payable"
  >;

  createTokenPocket: TypedContractMethod<
    [
      token: AddressLike,
      amount: BigNumberish,
      totalCount: BigNumberish,
      isLuckyDraw: boolean,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      expiresAt: BigNumberish,
      platform: string,
      channelId: string
    ],
    [bigint],
    "nonpayable"
  >;

  deactivatePocket: TypedContractMethod<
    [pocketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPocket: TypedContractMethod<
    [pocketId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        creator: string;
        token: string;
        totalAmount: bigint;
        remainingAmount: bigint;
        totalCount: bigint;
        claimedCount: bigint;
        expiresAt: bigint;
        isLuckyDraw: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isExpired: TypedContractMethod<[pocketId: BigNumberish], [boolean], "view">;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pocketCounter: TypedContractMethod<[], [bigint], "view">;

  pockets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string
      ] & {
        creator: string;
        token: string;
        totalAmount: bigint;
        remainingAmount: bigint;
        totalCount: bigint;
        claimedCount: bigint;
        minAmount: bigint;
        maxAmount: bigint;
        expiresAt: bigint;
        isLuckyDraw: boolean;
        isActive: boolean;
        platform: string;
        channelId: string;
      }
    ],
    "view"
  >;

  recoverExpired: TypedContractMethod<
    [pocketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setOperator: TypedContractMethod<
    [operator: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  socialIdClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ETH_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_EXPIRY_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_EXPIRY_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canClaim"
  ): TypedContractMethod<
    [pocketId: BigNumberish, claimer: AddressLike, socialIdHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [pocketId: BigNumberish, claimer: AddressLike, socialIdHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimDirect"
  ): TypedContractMethod<
    [pocketId: BigNumberish, socialIdHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createETHPocket"
  ): TypedContractMethod<
    [
      totalCount: BigNumberish,
      isLuckyDraw: boolean,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      expiresAt: BigNumberish,
      platform: string,
      channelId: string
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createTokenPocket"
  ): TypedContractMethod<
    [
      token: AddressLike,
      amount: BigNumberish,
      totalCount: BigNumberish,
      isLuckyDraw: boolean,
      minAmount: BigNumberish,
      maxAmount: BigNumberish,
      expiresAt: BigNumberish,
      platform: string,
      channelId: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivatePocket"
  ): TypedContractMethod<[pocketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPocket"
  ): TypedContractMethod<
    [pocketId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        creator: string;
        token: string;
        totalAmount: bigint;
        remainingAmount: bigint;
        totalCount: bigint;
        claimedCount: bigint;
        expiresAt: bigint;
        isLuckyDraw: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isExpired"
  ): TypedContractMethod<[pocketId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pocketCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pockets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string
      ] & {
        creator: string;
        token: string;
        totalAmount: bigint;
        remainingAmount: bigint;
        totalCount: bigint;
        claimedCount: bigint;
        minAmount: bigint;
        maxAmount: bigint;
        expiresAt: bigint;
        isLuckyDraw: boolean;
        isActive: boolean;
        platform: string;
        channelId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recoverExpired"
  ): TypedContractMethod<[pocketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [operator: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "socialIdClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PocketClaimed"
  ): TypedContractEvent<
    PocketClaimedEvent.InputTuple,
    PocketClaimedEvent.OutputTuple,
    PocketClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PocketCreated"
  ): TypedContractEvent<
    PocketCreatedEvent.InputTuple,
    PocketCreatedEvent.OutputTuple,
    PocketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PocketExpired"
  ): TypedContractEvent<
    PocketExpiredEvent.InputTuple,
    PocketExpiredEvent.OutputTuple,
    PocketExpiredEvent.OutputObject
  >;

  filters: {
    "OperatorUpdated(address,bool)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PocketClaimed(uint256,address,bytes32,uint256)": TypedContractEvent<
      PocketClaimedEvent.InputTuple,
      PocketClaimedEvent.OutputTuple,
      PocketClaimedEvent.OutputObject
    >;
    PocketClaimed: TypedContractEvent<
      PocketClaimedEvent.InputTuple,
      PocketClaimedEvent.OutputTuple,
      PocketClaimedEvent.OutputObject
    >;

    "PocketCreated(uint256,address,address,uint256,uint256,bool,uint256)": TypedContractEvent<
      PocketCreatedEvent.InputTuple,
      PocketCreatedEvent.OutputTuple,
      PocketCreatedEvent.OutputObject
    >;
    PocketCreated: TypedContractEvent<
      PocketCreatedEvent.InputTuple,
      PocketCreatedEvent.OutputTuple,
      PocketCreatedEvent.OutputObject
    >;

    "PocketExpired(uint256,uint256,address)": TypedContractEvent<
      PocketExpiredEvent.InputTuple,
      PocketExpiredEvent.OutputTuple,
      PocketExpiredEvent.OutputObject
    >;
    PocketExpired: TypedContractEvent<
      PocketExpiredEvent.InputTuple,
      PocketExpiredEvent.OutputTuple,
      PocketExpiredEvent.OutputObject
    >;
  };
}
