/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SimpleAccountFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accountExists"
      | "accountImplementation"
      | "createAccount"
      | "getAccountBySocialId"
      | "getAddress"
      | "socialIdToAccount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AccountCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "accountExists",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "accountImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAccount",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountBySocialId",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "socialIdToAccount",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountBySocialId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "socialIdToAccount",
    data: BytesLike
  ): Result;
}

export namespace AccountCreatedEvent {
  export type InputTuple = [
    account: AddressLike,
    owner: AddressLike,
    platform: string,
    socialId: string,
    salt: BytesLike
  ];
  export type OutputTuple = [
    account: string,
    owner: string,
    platform: string,
    socialId: string,
    salt: string
  ];
  export interface OutputObject {
    account: string;
    owner: string;
    platform: string;
    socialId: string;
    salt: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleAccountFactory extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleAccountFactory;
  waitForDeployment(): Promise<this>;

  interface: SimpleAccountFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accountExists: TypedContractMethod<
    [platform: string, socialId: string],
    [boolean],
    "view"
  >;

  accountImplementation: TypedContractMethod<[], [string], "view">;

  createAccount: TypedContractMethod<
    [owner: AddressLike, platform: string, socialId: string],
    [string],
    "nonpayable"
  >;

  getAccountBySocialId: TypedContractMethod<
    [platform: string, socialId: string],
    [string],
    "view"
  >;

  getAddress: TypedContractMethod<
    [owner: AddressLike, platform: string, socialId: string],
    [string],
    "view"
  >;

  socialIdToAccount: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accountExists"
  ): TypedContractMethod<
    [platform: string, socialId: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "accountImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createAccount"
  ): TypedContractMethod<
    [owner: AddressLike, platform: string, socialId: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAccountBySocialId"
  ): TypedContractMethod<
    [platform: string, socialId: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<
    [owner: AddressLike, platform: string, socialId: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "socialIdToAccount"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getEvent(
    key: "AccountCreated"
  ): TypedContractEvent<
    AccountCreatedEvent.InputTuple,
    AccountCreatedEvent.OutputTuple,
    AccountCreatedEvent.OutputObject
  >;

  filters: {
    "AccountCreated(address,address,string,string,bytes32)": TypedContractEvent<
      AccountCreatedEvent.InputTuple,
      AccountCreatedEvent.OutputTuple,
      AccountCreatedEvent.OutputObject
    >;
    AccountCreated: TypedContractEvent<
      AccountCreatedEvent.InputTuple,
      AccountCreatedEvent.OutputTuple,
      AccountCreatedEvent.OutputObject
    >;
  };
}
